version: '2.4'

services:
  db:
    container_name: wiper-db
    image: "mariadb:10.4"
    restart: always
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_DATABASE: languagetool
      MYSQL_ROOT_PASSWORD: languagetool
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    ports:
      - "8023:3306"
    volumes:
      - wiper-db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  parsoid:
    container_name: parsoid
    image: "thenets/parsoid:0.11"
    restart: always
    environment:
      PARSOID_DOMAIN_wikipedia_ca: https://ca.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_de: https://de.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_en: https://en.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_fr: https://fr.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_nl: https://nl.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_pl: https://pl.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_pt: https://pt.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_ru: https://ru.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_sv: https://sv.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_uk: https://uk.wikipedia.org/w/api.php
      PARSOID_NUM_WORKERS: ncpu
      PARSOID_STRICT_SSL: "false"
    ports:
      - "8024:8000"

  languagetool:
    container_name: languagetool-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: languagetool-server
    volumes:
      - ./server.properties:/home/server.properties
      - dumps:/home/dumps
    restart: always

  import:
    container_name: wiper-import
    depends_on:
      - db
      - parsoid
    build:
      context: .
      dockerfile: Dockerfile
      target: languagetool-wikipedia
    volumes:
      - dumps:/home/dumps
      - ./nwords:/home/nwords
      - ./server.prod.properties:/home/server.properties
    restart: always

volumes:
  wiper-db:
  dumps:
