version: '2.4'

services:
  db:
    container_name: wiper-db
    image: "mariadb:10.4"
    restart: always
    networks:
      default:
        aliases:
          - db
    environment:
      MYSQL_DATABASE: languagetool
      MYSQL_ROOT_PASSWORD: languagetool
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - wiper-db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  parsoid:
    container_name: parsoid
    image: "thenets/parsoid:0.11"
    restart: always
    networks:
      default:
        aliases:
          - parsoid
    environment:
      PARSOID_DOMAIN_wikipedia_ca: https://ca.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_de: https://de.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_en: https://en.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_fr: https://fr.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_nl: https://nl.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_pl: https://pl.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_pt: https://pt.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_ru: https://ru.wikipedia.org/w/api.php
      PARSOID_DOMAIN_wikipedia_uk: https://uk.wikipedia.org/w/api.php
      PARSOID_NUM_WORKERS: ncpu
      PARSOID_STRICT_SSL: "false"

  languagetool:
    container_name: languagetool-server
    depends_on:
      - db
    image: "bperel/languagetool-wiper"
    volumes:
      - ./server.properties:/home/server.properties
    restart: always
    networks:
      default:
        aliases:
          - languagetool
      workspace_global-front-network:
        aliases:
          - languagetool

  import:
    container_name: wiper-import
    depends_on:
      - db
      - parsoid
    image: "bperel/languagetool-wiper-import"
    volumes:
      - dumps:/home/dumps
      - ./nwords:/home/nwords
      - ./server.properties:/home/server.properties
    restart: always
    networks:
      default:
        aliases:
          - import

volumes:
  wiper-db:
  dumps:

networks:
  default:
    driver: bridge
  workspace_global-front-network:
    external: true
